name: Deploy Next.js to FTP

on:
  push:
    branches:
      - main # or your default branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build and export Next.js app
        run: npm run build

      - name: Show contents of out folder
        run: ls -la ./out/

      - name: Add cache-busting timestamp
        run: echo "Deployed at: $(date)" > ./out/deployment-timestamp.txt

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.arakash.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./out/
          server-dir: /public_html/ # <-- Update this to your actual root folder
          security: loose
          dry-run: false
          log-level: verbose
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/node_modules/**
            **/.DS_Store
            **/.env*
