name: Deploy Next.js to FTP (Full Replace)

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build and export static site
        run: |
          npm run build

      - name: Add deployment timestamp (optional)
        run: |
          echo "Built at: $(date)" > ./out/deployment-timestamp.txt

      - name: Deploy via FTP (full replace)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.arakash.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /
          security: loose
          dry-run: false
          log-level: verbose
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/node_modules/**
            **/.DS_Store
            **/.env*
